import 'package:flutter/foundation.dart';
import 'package:flutter_soloud/flutter_soloud.dart';
import 'package:shared_preferences/shared_preferences.dart';

// Clips are generated by tool/make_sounds.py. WAV rather than MP3 so the
// fire sound starts instantly (MP3 adds a few ms of encoder padding).
const _kFireAssets = {
  1: 'assets/sounds/fire_1.wav',
  2: 'assets/sounds/fire_2.wav',
  3: 'assets/sounds/fire_3.wav',
  4: 'assets/sounds/fire_4.wav',
  5: 'assets/sounds/fire_5.wav',
  6: 'assets/sounds/fire_6.wav',
  7: 'assets/sounds/fire_7.wav',
};
const _kExplosion = 'assets/sounds/explosion.wav';
const _kMiss = 'assets/sounds/miss.wav';
const _kDud = 'assets/sounds/dud.wav';
const _kGameOver = 'assets/sounds/game_over.wav';
const _kStart = 'assets/sounds/start.wav';

const _kSoundOn = 'sound_on';

/// Sound effects through SoLoud, same engine as rigobert: every clip is
/// decoded to PCM once up front and mixed natively, so playing is instant
/// and never blocks the platform thread.
///
/// Until [init] has run (e.g. in widget tests) every play call is a no-op.
class SoundService extends ChangeNotifier {
  static final SoundService _instance = SoundService._();
  factory SoundService() => _instance;
  SoundService._();

  static SoLoud get _engine => SoLoud.instance;

  final Map<String, AudioSource> _sources = {};
  bool _enabled = true;

  /// Whether sound is switched on (the mute button); persisted.
  bool get enabled => _enabled;

  Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    _enabled = prefs.getBool(_kSoundOn) ?? true;
    try {
      if (!_engine.isInitialized) {
        await _engine.init();
        _engine.setMaxActiveVoiceCount(12);
      }
      for (final asset in [
        ..._kFireAssets.values,
        _kExplosion,
        _kMiss,
        _kDud,
        _kGameOver,
        _kStart,
      ]) {
        _sources[asset] = await _engine.loadAsset(asset);
      }
    } catch (e) {
      debugPrint('[SoundService] init failed, playing silently: $e');
    }
    notifyListeners();
  }

  Future<void> toggle() async {
    _enabled = !_enabled;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_kSoundOn, _enabled);
  }

  void _play(String asset, {double volume = 1}) {
    if (!_enabled) return;
    final source = _sources[asset];
    if (source == null) return;
    _engine.play(source, volume: volume);
  }

  void fire(int mask) => _play(_kFireAssets[mask] ?? _kFireAssets[7]!);
  void explosion() => _play(_kExplosion);
  void miss() => _play(_kMiss);
  void dud() => _play(_kDud);
  void gameOver() => _play(_kGameOver);
  void start() => _play(_kStart);
}
